// generated by scripts/gen-assets.ts — do not edit by hand.
// Regenerate with: bun run scripts/gen-assets.ts
import type { HarnessCapabilitiesFile } from "./types.ts";
export const CAPABILITIES: HarnessCapabilitiesFile = {
  "schema_version": 1,
  "shared_workbench_projection": [
    ".agents/skills"
  ],
  "harnesses": {
    "claude": {
      "headless": [
        "claude",
        "-p"
      ],
      "argv_flags": {
        "permission": "--allowedTools",
        "tools_value": "Bash,Read,Write,Edit,mcp__gbrain__*",
        "output": "--output-format",
        "output_value": "text"
      },
      "sessions": [
        {
          "name": "SessionStart",
          "source": "hook"
        },
        {
          "name": "UserPromptSubmit",
          "source": "hook"
        }
      ],
      "mcp": {
        "native": true
      },
      "mcp_config": {
        "path": "~/.claude.json",
        "format": "json",
        "server_key": "mcpServers.gbrain"
      },
      "workbench_projection": [
        ".claude/skills"
      ],
      "user_install": [],
      "hook_format": "claude_settings_json",
      "native_memory": "none",
      "lifecycle": {
        "session_start": "best_effort",
        "session_end": "manual",
        "fallback": "manual",
        "crash_recovery": "best_effort"
      },
      "cron_harness_enum_value": "claude",
      "documented": true
    },
    "grok": {
      "headless": [
        "grok",
        "-p"
      ],
      "argv_flags": {
        "permission": "--allow",
        "tools_value": "Bash(*)",
        "output": "--output-format",
        "output_value": "json"
      },
      "sessions": [
        {
          "name": "SessionStart",
          "source": "hook"
        },
        {
          "name": "UserPromptSubmit",
          "source": "hook"
        },
        {
          "name": "PreCompact",
          "source": "hook"
        },
        {
          "name": "SessionEnd",
          "source": "hook"
        }
      ],
      "mcp": {
        "native": true
      },
      "mcp_config": {
        "path": "~/.grok/config.toml",
        "format": "toml",
        "server_key": "mcp_servers.gbrain"
      },
      "workbench_projection": [
        ".grok/skills"
      ],
      "user_install": [],
      "hook_format": "grok_hooks_json",
      "native_memory": "full",
      "lifecycle": {
        "session_start": "best_effort",
        "session_end": "best_effort",
        "fallback": "manual",
        "crash_recovery": "best_effort"
      },
      "cron_harness_enum_value": "grok",
      "documented": true
    },
    "opencode": {
      "headless": [
        "opencode",
        "run"
      ],
      "argv_flags": {},
      "sessions": [
        {
          "name": "session.created",
          "source": "plugin"
        },
        {
          "name": "session.idle",
          "source": "plugin"
        },
        {
          "name": "experimental.session.compacting",
          "source": "plugin"
        }
      ],
      "mcp": {
        "native": true
      },
      "mcp_config": null,
      "workbench_projection": [
        ".opencode/skills"
      ],
      "user_install": [],
      "hook_format": "opencode_plugin_ts",
      "native_memory": "none",
      "lifecycle": {
        "session_start": "best_effort",
        "session_end": "manual",
        "fallback": "manual",
        "crash_recovery": "best_effort"
      },
      "cron_harness_enum_value": "opencode",
      "documented": true
    },
    "pi": {
      "headless": [
        "pi",
        "-p"
      ],
      "argv_flags": {},
      "sessions": [
        {
          "name": "session_start",
          "source": "extension"
        },
        {
          "name": "before_agent_start",
          "source": "extension"
        }
      ],
      "mcp": {
        "via": "pi_mcp_adapter"
      },
      "mcp_config": null,
      "workbench_projection": [],
      "user_install": [
        "~/.agents/skills"
      ],
      "hook_format": "none",
      "native_memory": "none",
      "lifecycle": {
        "session_start": "best_effort",
        "session_end": "manual",
        "fallback": "manual",
        "crash_recovery": "best_effort"
      },
      "cron_harness_enum_value": "pi",
      "documented": true
    },
    "cursor": {
      "headless": null,
      "argv_flags": {},
      "sessions": [
        {
          "name": "sessionStart",
          "source": "hook"
        }
      ],
      "mcp": {
        "native": true
      },
      "mcp_config": null,
      "workbench_projection": [],
      "user_install": [],
      "hook_format": "cursor_hooks_json",
      "native_memory": "none",
      "lifecycle": {
        "session_start": "best_effort",
        "session_end": "manual",
        "fallback": "manual",
        "crash_recovery": "manual"
      },
      "cron_harness_enum_value": null,
      "documented": true
    },
    "codex": {
      "headless": [
        "codex",
        "exec"
      ],
      "argv_flags": {},
      "sessions": [],
      "mcp": {
        "native": true
      },
      "mcp_config": null,
      "workbench_projection": [],
      "user_install": [],
      "hook_format": "none",
      "native_memory": "none",
      "lifecycle": {
        "session_start": "manual",
        "session_end": "manual",
        "fallback": "manual",
        "crash_recovery": "best_effort"
      },
      "cron_harness_enum_value": "codex",
      "documented": false
    }
  }
};
