// cli/embed.ts — dev-root resolution + embedded asset tree materialization.
// Compiled binary embeds templates/workbench + skills via assets.generated.ts
// (generated by scripts/gen-assets.ts), so a standalone `jspace` needs nothing
// on disk except itself. Ground truth: research/empirical-bun-probe.md.
import { basename, dirname, join, resolve } from "node:path";
import { homedir } from "node:os";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fail } from "../core/shared/errors.ts";
import { ASSETS } from "./assets.generated.ts";
import { SKILLS_MANIFEST } from "./skills.generated.ts";
import { replaceAgentsBlock } from "../application/workspace/agents-block.ts";
import { materializedRels } from "../application/workspace/manifest.ts";

export const PLACEHOLDER = "__DEV_ROOT__";

/** True when running as a standalone compiled executable. bun embeds its FS at
 *  /$bunfs/ on POSIX and on a drive-letter mount (B:\~BUN\...) on Windows. */
export function isCompiled(): boolean {
  const a1 = process.argv[1];
  if (typeof a1 === "string" && (a1.startsWith("/$bunfs/") || a1.includes("~BUN") || a1.includes("bunfs"))) {
    return true;
  }
  return typeof process.execPath === "string" && /~BUN|bunfs/i.test(process.execPath);
}

/** CLI install/source root:
 *  - compiled: directory containing the standalone binary, except the standard
 *    build layout (binary at <repo>/bin/jspace) resolves to the repo root
 *  - source:   repo root (cli/ -> ..)
 */
export function devRoot(): string {
  if (isCompiled()) {
    const d = dirname(process.execPath);
    // `bun run build` puts the binary in <repo>/bin/jspace — the dev root is
    // the repo (one level up), not bin/. Standalone installs not in a "bin"
    // dir keep their own directory.
    return basename(d) === "bin" ? dirname(d) : d;
  }
  // source: this module is cli/embed.ts -> repo root
  return resolve(import.meta.dir, "..");
}

export function expandTilde(p: string): string {
  if (p === "~") return homedir();
  if (p.startsWith("~/") || p.startsWith("~\\")) return join(homedir(), p.slice(2));
  if (p.startsWith("~")) {
    // ~user → that user's home (best-effort; Python uses the OS user database)
    const name = p.slice(1).split(/[\\/]/)[0];
    const rest = p.slice(1 + name.length);
    const base =
      process.platform === "win32"
        ? homedir()
        : process.platform === "darwin"
          ? `/Users/${name}`
          : `/home/${name}`;
    return join(base, rest);
  }
  return p;
}

function hasAssets(prefix: string): boolean {
  return Object.keys(ASSETS).some((k) => k.startsWith(prefix));
}

/** Read an existing target-relative file, or null when absent. */
function readExisting(target: string, rel: string): string | null {
  try {
    return readFileSync(join(target, rel), "utf-8");
  } catch {
    return null;
  }
}

/** JSON-escape a replacement value (backslashes/quotes) so a Windows path
 *  injected into a .json template produces valid JSON (e.g. B:\~BUN\bin). */
function jsonEscape(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/**
 * Write the embedded tree into `target`, replacing __DEV_ROOT__ placeholders.
 * JSON assets escape the replacement (Windows paths contain backslashes that
 * would otherwise produce invalid JSON). Official skills materialize into the
 * hidden .jspace/skills/ (root `skills/` is reserved for user-created skills);
 * filehub is created on demand by `filehub init`.
 */
export function materializeTree(target: string, devRootStr: string): void {
  if (!hasAssets("templates/workbench/")) {
    fail("workbench template assets missing in embedded bundle");
  }
  // Every manifest-declared workbench skill must be embedded (F2: this now
  // includes memory-recall / memory-writeback, not just jspace-use+asset-ingest).
  for (const s of SKILLS_MANIFEST.workbench) {
    if (!hasAssets(`skills/${s.name}/`)) {
      fail(`skill assets missing: skills/${s.name}`);
    }
  }
  for (const [key, content] of Object.entries(ASSETS)) {
    if (key.startsWith("templates/filehub/")) {
      continue; // filehub skeleton is materialized on demand by `filehub init`
    }
    // One manifest key may materialize to several paths (official skills also
    // project into harness dirs, e.g. .claude/skills/); the rel mapping lives
    // in materializedRels so embed and diff/upgrade can never drift apart.
    const rels = materializedRels(key);
    if (rels.length === 0) {
      throw new Error(`unexpected asset key: ${key}`);
    }
    const replacement = key.endsWith(".json") ? jsonEscape(devRootStr) : devRootStr;
    for (const rel of rels) {
      const out = join(target, rel);
      mkdirSync(dirname(out), { recursive: true });
      let bytes = content.replaceAll(PLACEHOLDER, replacement);
      if (rel === "AGENTS.md") {
        // JSpace owns only the JSPACE block inside AGENTS.md, never the whole file.
        // When a user file already exists (e.g. --force into a non-empty dir),
        // embed/replace the block and preserve everything outside it.
        const existing = readExisting(target, rel);
        if (existing !== null) bytes = replaceAgentsBlock(existing, bytes);
      }
      writeFileSync(out, bytes, "utf-8");
    }
  }
}

/** The embedded filehub root README (templates/filehub/README.md). */
export function filehubReadme(devRootStr: string): string {
  const key = "templates/filehub/README.md";
  const content = ASSETS[key];
  if (content === undefined) {
    fail(`filehub template missing in embedded bundle: ${key} (run bun run scripts/gen-assets.ts)`);
  }
  return content.replaceAll(PLACEHOLDER, devRootStr);
}
