// cli/embed.ts — dev-root resolution + embedded asset tree materialization.
// Compiled binary embeds templates/workbench + skills via assets.generated.ts
// (generated by scripts/gen-assets.ts), so a standalone `jspace` needs nothing
// on disk except itself. Ground truth: research/empirical-bun-probe.md.
import { dirname, join, resolve } from "node:path";
import { homedir } from "node:os";
import { mkdirSync, writeFileSync } from "node:fs";
import { ASSETS } from "./assets.generated.ts";

export const PLACEHOLDER = "__DEV_ROOT__";

/** True when running as a standalone compiled executable (bun embeds FS at /$bunfs/). */
export function isCompiled(): boolean {
  const a1 = process.argv[1];
  return typeof a1 === "string" && a1.startsWith("/$bunfs/");
}

/** CLI install/source root:
 *  - compiled: directory containing the standalone binary
 *  - source:   repo root (cli/ -> ..)
 */
export function devRoot(): string {
  if (isCompiled()) return dirname(process.execPath);
  // source: this module is cli/embed.ts -> repo root
  return resolve(import.meta.dir, "..");
}

export function expandTilde(p: string): string {
  if (p === "~") return homedir();
  if (p.startsWith("~/") || p.startsWith("~\\")) return join(homedir(), p.slice(2));
  return p;
}

function hasTemplateAssets(): boolean {
  return Object.keys(ASSETS).some((k) => k.startsWith("templates/workbench/"));
}

/**
 * Write the embedded tree into `target`, replacing __DEV_ROOT__ placeholders.
 * Mirrors Python: shutil.copytree(template, target, dirs_exist_ok=True) +
 * copy of skills/{jspace-bootstrap,asset-ingest} + _materialize_placeholders.
 */
export function materializeTree(target: string, devRootStr: string): void {
  if (!hasTemplateAssets()) {
    throw new Error("workbench template assets missing in embedded bundle");
  }
  for (const [key, content] of Object.entries(ASSETS)) {
    let rel: string;
    if (key.startsWith("templates/workbench/")) {
      rel = key.slice("templates/workbench/".length);
    } else if (key.startsWith("skills/")) {
      rel = key; // keep skills/<name>/...
    } else {
      throw new Error(`unexpected asset key: ${key}`);
    }
    const out = join(target, rel);
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, content.replaceAll(PLACEHOLDER, devRootStr), "utf-8");
  }
}
