// generated by scripts/gen-assets.ts — do not edit by hand.
// Regenerate with: bun run scripts/gen-assets.ts
import type { DistributionManifestV1 } from "../core/contracts/distribution.ts";
export const BUNDLE_MANIFEST: DistributionManifestV1 = {
  version: 1,
  bundle_version: "1.0.2",
  files: [
  { path: "templates/workbench/.claude/settings.json", sha256: "386ad5c0573f9c72414b5a8b820428ee4d72e4849bbd5bb19156ee342fd75c9b", ownership: "managed" },
  { path: "templates/workbench/.jspace/cron.json", sha256: "a51b9dd452940ff660bf3093be33e6608408b3dc6c12c5f13bc3819791b2279e", ownership: "managed" },
  { path: "templates/workbench/.jspace/hub.json", sha256: "d30ccf5cbcfd59ef4e5d2d21ef989d59c831587614a6ec66cb2d91c4441b55e7", ownership: "managed" },
  { path: "templates/workbench/README.md", sha256: "332a335cf70f38ce11a2706b28205a338696cfcea188650567180c118faeb1c3", ownership: "managed" },
  { path: "templates/workbench/.gitignore", sha256: "0f2e16c43f69d5da1cbffb1ff533c71f45eebe132b475471f0c014f6d204fd55", ownership: "managed" },
  { path: "templates/workbench/AGENTS.md", sha256: "93e04a512631683f6000f2e9e1e03d46af2815d1ba0b5c44e1ad9c867917845b", ownership: "managed" },
  { path: "templates/filehub/README.md", sha256: "c2718edc9f96d2f4a589256dd423b688d12ffd66ab6574ae2345bb16f489a730", ownership: "managed" },
  { path: "skills/jspace-bootstrap/references/gbrain.md", sha256: "380961bf70832dd0a8b4a5887e0da1fb647d564289afbd0cae05216abf3825ee", ownership: "seed" },
  { path: "skills/jspace-bootstrap/references/harnesses.md", sha256: "5a8f4db5b5752681e309d27bf4679318cbad1a4f9829c24a2e26d767ec9eb3a9", ownership: "seed" },
  { path: "skills/jspace-bootstrap/references/registry.md", sha256: "fbab4b4399317e43f7bba1fad8f15b6e85be0b1b6eea2aa3d558868f94ee8283", ownership: "seed" },
  { path: "skills/jspace-bootstrap/agents/openai.yaml", sha256: "d6fb2598ad72ff41a22e59ebe0f2ccc644791a816065176b3115bc0e2ee9e371", ownership: "seed" },
  { path: "skills/jspace-bootstrap/SKILL.md", sha256: "9ac8c36789c78cce7d07c16007c9cb1d15467987ef088f43661bf2aaae923c2a", ownership: "seed" },
  { path: "skills/asset-ingest/references/deep-extract.md", sha256: "570a2a944a578eb3beb827ccc82843a06d4753713080b05fc4df320b9d7998ee", ownership: "seed" },
  { path: "skills/asset-ingest/references/migration.md", sha256: "f3d380873c27786e2657a7fa299d9d3fe3ef48b67d00e81c6238eb6eb4d6170a", ownership: "seed" },
  { path: "skills/asset-ingest/references/gbrain-write.md", sha256: "d96cd8ecee502f5d57d2a8edc2d0d64c4b5f945fd68d2c040a7d52f21e7a4b78", ownership: "seed" },
  { path: "skills/asset-ingest/references/filing.md", sha256: "b29859f0761ecc43d4c0d8948062dd6e9d0624c611ab5c45937dc7aa9e3e819b", ownership: "seed" },
  { path: "skills/asset-ingest/references/batch.md", sha256: "a8d3a75c80d26ed123ec87f356a28d65405524f4c7663c121bace46db4a6b57d", ownership: "seed" },
  { path: "skills/asset-ingest/scripts/office-extract.test.py", sha256: "e57794b858ba05b0a4cd8379af0a3ffad55b7b4559db705ef04ad13a5e4e2daa", ownership: "seed" },
  { path: "skills/asset-ingest/scripts/office-extract.py", sha256: "5fac27c07e98f255c8f548b1326ec53dc818a18e325b67a25a2593f9f06f26df", ownership: "seed" },
  { path: "skills/asset-ingest/SKILL.md", sha256: "a04adde501c3517e7c89cd8fffe820e9aadd86bc1d8e4ef463bca515b48ead1d", ownership: "seed" },
  ],
};
