// generated by scripts/gen-assets.ts — do not edit by hand.
// Regenerate with: bun run scripts/gen-assets.ts
import type { SkillsManifestV1 } from "../core/contracts/skills.ts";
export const SKILLS_MANIFEST: SkillsManifestV1 = {
  "schema_version": 1,
  "workbench": [
    {
      "name": "jspace-use",
      "version": "1",
      "scope": "workbench",
      "dependencies": []
    },
    {
      "name": "asset-ingest",
      "version": "1",
      "scope": "workbench",
      "dependencies": [],
      "entrypoints": [
        "batch"
      ]
    },
    {
      "name": "memory-recall",
      "version": "1",
      "scope": "workbench",
      "dependencies": [
        "asset-ingest"
      ]
    },
    {
      "name": "memory-writeback",
      "version": "1",
      "scope": "workbench",
      "dependencies": [
        "asset-ingest",
        "jspace-use"
      ]
    },
    {
      "name": "workbench-retro",
      "version": "1",
      "scope": "workbench",
      "dependencies": [
        "jspace-use",
        "memory-writeback",
        "asset-ingest"
      ],
      "entrypoints": [
        "weekly"
      ]
    },
    {
      "name": "weekly-report",
      "version": "1",
      "scope": "workbench",
      "dependencies": [
        "jspace-use",
        "asset-ingest",
        "memory-consolidate"
      ],
      "entrypoints": [
        "weekly"
      ]
    },
    {
      "name": "memory-consolidate",
      "version": "1",
      "scope": "workbench",
      "dependencies": [
        "jspace-use",
        "memory-writeback"
      ],
      "entrypoints": [
        "weekly"
      ]
    }
  ],
  "global": [
    {
      "name": "harness-config",
      "version": "1",
      "scope": "global",
      "dependencies": [],
      "install_path": "~/.agents/skills/harness-config"
    }
  ]
};
