// scripts/asset-integrity.ts — pure helpers for the gen-assets source-integrity
// guard (issue #6). A committed generated manifest whose path has no source on
// disk means the bundle holds stale bytes that a fresh clone's gen-assets would
// silently drop — the exact .opencode-plugin-loss bug. These are pure so the
// guard is unit-testable without running the gen-assets side effects.
//
// Intentional removals (e.g. dropping a skill) hit the guard too; rerun with
// GEN_ASSETS_ALLOW_MISSING=1 to regenerate-and-drop the stale entries, then
// commit the regenerated files.

import { readFileSync } from "node:fs";

/** Extract the file paths from a committed cli/manifest.generated.ts
 *  (BUNDLE_MANIFEST.files[].path literals). The file is TypeScript, not JSON,
 *  so paths are matched from the generated `{ path: "...", ... }` rows.
 *
 *  LEGACY (issue #7 P3.16): checks now read cli/manifest.json via
 *  readManifestJson instead — regexing the whole TS is fragile (a `path:`
 *  string in a comment/import line or a quote inside a path mis-matches). Kept
 *  for the asset-integrity unit tests that pin the historical extraction. */
export function manifestPaths(manifestTs: string): string[] {
  const out: string[] = [];
  const re = /\bpath:\s*"([^"]+)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(manifestTs)) !== null) out.push(m[1]);
  return out;
}

/** Read the committed cli/manifest.json (pure JSON twin of BUNDLE_MANIFEST,
 *  generated by gen-assets alongside manifest.generated.ts). The single parse
 *  path for all manifest checks — no regex over generated TypeScript. */
export interface ManifestFileEntry {
  path: string;
  sha256: string;
  ownership: string;
}
export function readManifestJson(manifestJsonPath: string): { files: ManifestFileEntry[] } {
  return JSON.parse(readFileSync(manifestJsonPath, "utf-8")) as { files: ManifestFileEntry[] };
}

/** Paths the previous generated manifest declared that the current walk cannot
 *  produce. Non-empty = source files were deleted without regenerating
 *  (silent decay). Deduplicated; order follows the manifest. */
export function staleManifestPaths(oldPaths: string[], newPaths: Iterable<string>): string[] {
  const have = new Set(newPaths);
  return [...new Set(oldPaths)].filter((p) => !have.has(p));
}
