// scripts/asset-integrity.test.ts — source-integrity guard helpers (issue #6).
// The gen-assets assert turns a silent source-file loss into a loud exit 1;
// these pure helpers pin the extraction + staleness logic.
// Run: bun test scripts/asset-integrity.test.ts
import { expect, test } from "bun:test";
import { manifestPaths, staleManifestPaths } from "./asset-integrity.ts";

test("manifestPaths extracts path literals from the generated BUNDLE_MANIFEST (TS, not JSON)", () => {
  const ts = `// generated by scripts/gen-assets.ts — do not edit by hand.
export const BUNDLE_MANIFEST: DistributionManifestV1 = {
  schema_version: 1,
  bundle_version: "1.0.0",
  files: [
  { path: "templates/workbench/.claude/settings.json", sha256: "a", ownership: "seed" },
  { path: "templates/workbench/.opencode/plugins/jspace.ts", sha256: "b", ownership: "seed" },
  { path: "skills/jspace-use/SKILL.md", sha256: "c", ownership: "seed" },
  ],
};`;
  expect(manifestPaths(ts)).toEqual([
    "templates/workbench/.claude/settings.json",
    "templates/workbench/.opencode/plugins/jspace.ts",
    "skills/jspace-use/SKILL.md",
  ]);
});

test("manifestPaths is empty when there are no files rows", () => {
  expect(manifestPaths("export const BUNDLE_MANIFEST = { schema_version: 1, files: [] };")).toEqual([]);
});

test("staleManifestPaths flags an old path the new walk cannot produce (the bug class)", () => {
  // old manifest declares the plugin; the fresh-clone walk (source lost) can't
  // produce it — the guard must flag it, not silently drop it.
  const stale = staleManifestPaths(
    ["templates/workbench/.claude/settings.json", "templates/workbench/.opencode/plugins/jspace.ts"],
    new Set(["templates/workbench/.claude/settings.json"]),
  );
  expect(stale).toEqual(["templates/workbench/.opencode/plugins/jspace.ts"]);
});

test("staleManifestPaths is empty when every old path still has a source", () => {
  const paths = ["a.ts", "b/c.ts", "d/e/f.ts"];
  expect(staleManifestPaths(paths, new Set(paths))).toEqual([]);
});

test("staleManifestPaths dedupes repeated old paths and ignores extras", () => {
  expect(staleManifestPaths(["a", "b", "a"], new Set(["a", "c"]))).toEqual(["b"]);
});
