// scripts/gen-version.ts — emit cli/version.generated.ts from JSPACE_BUILD_VERSION
// (CI sets it from the git tag) or a git describe fallback. Run before every
// build so the compiled binary reports its real release version.
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "..");
const out = resolve(repoRoot, "cli/version.generated.ts");

let version = (process.env.JSPACE_BUILD_VERSION ?? "").trim();
if (!version) {
  try {
    version = execSync("git describe --tags --abbrev=0 2>/dev/null", {
      cwd: repoRoot,
      encoding: "utf-8",
    }).trim();
  } catch {
    version = "";
  }
}
if (!version) version = "0.0.0-dev";
// Display without the `v` prefix (matches `jspace 1.0.2`; update comparisons
// and download URLs already handle both forms).
version = version.replace(/^v/, "");

writeFileSync(
  out,
  `// GENERATED by scripts/gen-version.ts — do not edit.\nexport const VERSION = ${JSON.stringify(version)};\n`,
  "utf-8",
);
console.log(`wrote cli/version.generated.ts (VERSION=${version})`);
