// scripts/gen-assets.ts — walk templates/workbench + skills and emit
// cli/assets.generated.ts (content map) and cli/manifest.generated.ts
// (DistributionManifestV1 with sha256 + ownership). Embedded by bun build
// --compile for a self-contained binary. Regenerate after editing templates
// or skills.
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { extname, join, relative, resolve, sep } from "node:path";
import { ownershipFor, sha256Of } from "../application/workspace/manifest.ts";
import { VERSION } from "../cli/version.generated.ts";

const repoRoot = resolve(import.meta.dir, "..");
const SOURCES = ["templates/workbench", "templates/filehub", "skills/jspace-bootstrap", "skills/asset-ingest"];

// Skip VCS/build artifacts so they never get embedded into the binary.
const SKIP_DIRS = new Set(["__pycache__", ".git", "node_modules"]);
const SKIP_EXT = new Set([".pyc", ".pyo", ".DS_Store"]);

function walk(dir: string, base: string, out: Map<string, string>): void {
  for (const name of readdirSync(dir)) {
    if (SKIP_DIRS.has(name)) continue;
    const p = join(dir, name);
    if (statSync(p).isDirectory()) {
      walk(p, base, out);
    } else {
      if (SKIP_EXT.has(extname(name))) continue;
      const rel = relative(base, p).split(sep).join("/");
      const baseRel = relative(repoRoot, base).split(sep).join("/");
      out.set(`${baseRel}/${rel}`, readFileSync(p, "utf-8"));
    }
  }
}

const assets = new Map<string, string>();
for (const s of SOURCES) walk(join(repoRoot, s), join(repoRoot, s), assets);

const body = [...assets.entries()]
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  .join("\n");
const output = `// generated by scripts/gen-assets.ts — do not edit by hand.
// Regenerate with: bun run scripts/gen-assets.ts
export const ASSETS: Record<string, string> = {
${body}
};
`;
writeFileSync(join(repoRoot, "cli", "assets.generated.ts"), output, "utf-8");
console.log(`wrote cli/assets.generated.ts (${assets.size} files, ${output.length} bytes)`);

// Bundle manifest (DistributionManifestV1): per-file sha256 + ownership.
const manifestBody = [...assets.entries()]
  .map(
    ([k, v]) =>
      `  { path: ${JSON.stringify(k)}, sha256: "${sha256Of(v)}", ownership: "${ownershipFor(k)}" },`,
  )
  .join("\n");
const manifestOutput = `// generated by scripts/gen-assets.ts — do not edit by hand.
// Regenerate with: bun run scripts/gen-assets.ts
import type { DistributionManifestV1 } from "../core/contracts/distribution.ts";
export const BUNDLE_MANIFEST: DistributionManifestV1 = {
  version: 1,
  bundle_version: ${JSON.stringify(VERSION)},
  files: [
${manifestBody}
  ],
};
`;
writeFileSync(join(repoRoot, "cli", "manifest.generated.ts"), manifestOutput, "utf-8");
console.log(`wrote cli/manifest.generated.ts (${assets.size} files, ${manifestOutput.length} bytes)`);
