// scripts/gen-assets.ts — walk templates/workbench + skills and emit
// cli/assets.generated.ts (embedded by bun build --compile for a self-contained
// binary). Regenerate after editing templates or skills.
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve, sep } from "node:path";

const repoRoot = resolve(import.meta.dir, "..");
const SOURCES = ["templates/workbench", "skills/jspace-bootstrap", "skills/asset-ingest"];

function walk(dir: string, base: string, out: Map<string, string>): void {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) {
      walk(p, base, out);
    } else {
      const rel = relative(base, p).split(sep).join("/");
      const baseRel = relative(repoRoot, base).split(sep).join("/");
      out.set(`${baseRel}/${rel}`, readFileSync(p, "utf-8"));
    }
  }
}

const assets = new Map<string, string>();
for (const s of SOURCES) walk(join(repoRoot, s), join(repoRoot, s), assets);

const body = [...assets.entries()]
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  .join("\n");
const output = `// generated by scripts/gen-assets.ts — do not edit by hand.
// Regenerate with: bun run scripts/gen-assets.ts
export const ASSETS: Record<string, string> = {
${body}
};
`;
writeFileSync(join(repoRoot, "cli", "assets.generated.ts"), output, "utf-8");
console.log(`wrote cli/assets.generated.ts (${assets.size} files, ${output.length} bytes)`);
