// scripts/gen-assets.ts — walk templates/workbench + skills and emit
// cli/assets.generated.ts (content map) and cli/manifest.generated.ts
// (DistributionManifestV1 with sha256 + ownership). Embedded by bun build
// --compile for a self-contained binary. Regenerate after editing templates
// or skills.
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { extname, join, relative, resolve, sep } from "node:path";
import { ownershipFor, sha256Of } from "../application/workspace/manifest.ts";
import { decodeSkillsManifest } from "../core/contracts/skills.ts";
import { VERSION } from "../cli/version.generated.ts";

const repoRoot = resolve(import.meta.dir, "..");

// skills-manifest.json is the single source for which skills ship in the
// binary. gen-assets embeds every workbench-scoped skill dir (F2: this pulls
// memory-recall/writeback into the bundle) and asserts each exists on disk so
// the manifest never drifts from the skills/ tree.
const skillsRaw = JSON.parse(readFileSync(join(repoRoot, "skills-manifest.json"), "utf-8")) as unknown;
const skillsDecoded = decodeSkillsManifest(skillsRaw);
if (!skillsDecoded.ok) {
  throw new Error(
    `skills-manifest.json invalid: ${skillsDecoded.issues.map((i) => `${i.code}: ${i.message}`).join("; ")}`,
  );
}
const skillsManifest = skillsDecoded.value;
const skillDirs = skillsManifest.workbench.map((s) => `skills/${s.name}`);
for (const d of skillDirs) {
  if (!statSync(join(repoRoot, d), { throwIfNoEntry: false })?.isDirectory()) {
    throw new Error(`skills-manifest declares missing skill dir: ${d}`);
  }
}
const SOURCES = ["templates/workbench", "templates/filehub", ...skillDirs];

// Skip VCS/build artifacts so they never get embedded into the binary.
const SKIP_DIRS = new Set(["__pycache__", ".git", "node_modules"]);
const SKIP_EXT = new Set([".pyc", ".pyo", ".DS_Store"]);

function walk(dir: string, base: string, out: Map<string, string>): void {
  // deterministic traversal: readdir order differs across filesystems (APFS vs
  // ext4) and would make generated output non-reproducible / freshness-flaky.
  for (const name of readdirSync(dir).sort()) {
    if (SKIP_DIRS.has(name)) continue;
    const p = join(dir, name);
    if (statSync(p).isDirectory()) {
      walk(p, base, out);
    } else {
      if (SKIP_EXT.has(extname(name))) continue;
      const rel = relative(base, p).split(sep).join("/");
      const baseRel = relative(repoRoot, base).split(sep).join("/");
      out.set(`${baseRel}/${rel}`, readFileSync(p, "utf-8"));
    }
  }
}

const assets = new Map<string, string>();
for (const s of SOURCES) walk(join(repoRoot, s), join(repoRoot, s), assets);

const body = [...assets.entries()]
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  .join("\n");
const output = `// generated by scripts/gen-assets.ts — do not edit by hand.
// Regenerate with: bun run scripts/gen-assets.ts
export const ASSETS: Record<string, string> = {
${body}
};
`;
writeFileSync(join(repoRoot, "cli", "assets.generated.ts"), output, "utf-8");
console.log(`wrote cli/assets.generated.ts (${assets.size} files, ${output.length} bytes)`);

// Bundle manifest (DistributionManifestV1): per-file sha256 + ownership.
const manifestBody = [...assets.entries()]
  .map(
    ([k, v]) =>
      `  { path: ${JSON.stringify(k)}, sha256: "${sha256Of(v)}", ownership: "${ownershipFor(k)}" },`,
  )
  .join("\n");
const manifestOutput = `// generated by scripts/gen-assets.ts — do not edit by hand.
// Regenerate with: bun run scripts/gen-assets.ts
import type { DistributionManifestV1 } from "../core/contracts/distribution.ts";
export const BUNDLE_MANIFEST: DistributionManifestV1 = {
  version: 1,
  bundle_version: ${JSON.stringify(VERSION)},
  files: [
${manifestBody}
  ],
};
`;
writeFileSync(join(repoRoot, "cli", "manifest.generated.ts"), manifestOutput, "utf-8");
console.log(`wrote cli/manifest.generated.ts (${assets.size} files, ${manifestOutput.length} bytes)`);

// SkillsManifest embedded for runtime validation (validateSkillTarget reads
// which skills are required + their versions).
const skillsOutput = `// generated by scripts/gen-assets.ts — do not edit by hand.
// Regenerate with: bun run scripts/gen-assets.ts
import type { SkillsManifestV1 } from "../core/contracts/skills.ts";
export const SKILLS_MANIFEST: SkillsManifestV1 = ${JSON.stringify(skillsManifest, null, 2)};
`;
writeFileSync(join(repoRoot, "cli", "skills.generated.ts"), skillsOutput, "utf-8");
console.log(`wrote cli/skills.generated.ts (${JSON.stringify(skillsManifest.workbench.map((s) => s.name))})`);
