// scripts/gen-version.ts — emit cli/version.generated.ts from JSPACE_BUILD_VERSION
// (CI sets it from the git tag) or a git describe fallback. Run before every
// build so the compiled binary reports its real release version.
// Non-release builds carry the commit delta (git describe --tags gives
// `1.0.9-2-g7cef2bc` when HEAD leads the tag), so `--version` distinguishes a
// tag-point build from a leading-commits dev build. Release builds (tag) are
// still overwritten to the clean tag by JSPACE_BUILD_VERSION.
//
// RELEASE NOTE: bumping the version requires BOTH this script AND gen-assets.ts
// — gen-assets reads VERSION and embeds it as manifest `bundle_version`
// (cli/manifest.generated.ts / manifest.json). Missing the second step passes
// local tests but fails CI's asset-freshness (verify + build test), which skips
// the release job (v1.0.14 lesson: run `build:all`, never gen-version alone).
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "..");
const out = resolve(repoRoot, "cli/version.generated.ts");

let version = (process.env.JSPACE_BUILD_VERSION ?? "").trim();
if (!version) {
  try {
    version = execSync("git describe --tags 2>/dev/null", {
      cwd: repoRoot,
      encoding: "utf-8",
    }).trim();
  } catch {
    version = "";
  }
}
if (!version) version = "0.0.0-dev";
// Display without the `v` prefix (matches `jspace 1.0.2`; update comparisons
// and download URLs already handle both forms).
version = version.replace(/^v/, "");

writeFileSync(
  out,
  `// GENERATED by scripts/gen-version.ts — do not edit.\nexport const VERSION = ${JSON.stringify(version)};\n`,
  "utf-8",
);
console.log(`wrote cli/version.generated.ts (VERSION=${version})`);
